//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bl.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Cancelations = new HashSet<Cancelation>();
        }
    
        public int id { get; set; }
        public Nullable<int> BranchDayId { get; set; }
        public Nullable<System.DateTime> dateTimeTurn { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> getServiceDate { get; set; }
        public Nullable<int> DurationService { get; set; }
        public Nullable<int> RouteId { get; set; }
    
        public virtual ShiftDayDetail ShiftDayDetail { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelation> Cancelations { get; set; }
        public virtual Route Route { get; set; }
    }
}
