//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bl.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.ShiftDayDetails = new HashSet<ShiftDayDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> idBranch { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> MinTimeToCancel { get; set; }
        public Nullable<decimal> PaymentforCancel { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftDayDetail> ShiftDayDetails { get; set; }
    }
}
