//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bl.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftDayDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftDayDetail()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int id { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> openTime { get; set; }
        public Nullable<System.TimeSpan> ClosedTime { get; set; }
        public Nullable<double> avgServiceTime { get; set; }
        public Nullable<double> zGrade { get; set; }
        public Nullable<int> waitingTimeAvg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
