//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public Nullable<int> dayId { get; set; }
        public Nullable<System.DateTime> hour { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> getServiceDate { get; set; }
        public Nullable<double> DurationService { get; set; }
        public Nullable<int> business { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Day Day1 { get; set; }
        public virtual User User { get; set; }
        public virtual Cancelation Cancelation { get; set; }
    }
}
